/**
 * Site-wide content constants for Renova Life Care Ltd.
 * Edit this file to update all page content from a single location.
 */

import { SITE_URL } from "@/config";

export const siteConfig = {
  name: "Renova Life Care Ltd.",
  url: SITE_URL,
  slogan: "Caring Today, Healthy Tomorrow.",
  tagline: "Bangladesh's Most Trusted Health Services Provider",
  description:
    "Renova Life Care Ltd. delivers world-class healthcare services across Bangladesh. From general checkups to specialized treatments, our expert doctors are here for you.",
  phone: "+880 1700-000000",
  phoneAlt: "+880 1711-000000",
  email: "info@renovalifecare.com",
  emergencyEmail: "emergency@renovalifecare.com",
  address: {
    street: "House #12,",
    area: "Gulshan 2",
    city: "Dhaka-1212",
    country: "Bangladesh",
  },
  hours: {
    weekday: "Saturday – Thursday: 8:00 AM – 10:00 PM",
    weekend: "Friday: 10:00 AM – 6:00 PM",
    emergency: "Emergency: 24/7",
  },
  established: "2010",
};

export const stats = [
  { value: "15,000+", label: "Happy Patients", icon: "users" },
  { value: "120+", label: "Expert Doctors", icon: "stethoscope" },
  { value: "35+", label: "Departments", icon: "building" },
  { value: "14", label: "Years Experience", icon: "award" },
];

export const services = [
  {
    id: 1,
    title: "Pathology & Laboratory Testing",
    description: "Comprehensive laboratory analysis including blood, tissue, and fluid testing for accurate disease diagnosis.",
    icon: "test-tube",
    color: "#7c3aed",
    href: "/services/pathology-laboratory-testing",
  },
  {
    id: 2,
    title: "Blood Test & Biochemistry",
    description: "Advanced blood analysis to assess organ function, detect deficiencies, and monitor chronic conditions.",
    icon: "droplet",
    color: "#e53e3e",
    href: "/services/blood-test-biochemistry",
  },
  {
    id: 3,
    title: "Hematology Services",
    description: "Specialized testing for blood disorders, anemia, clotting issues, and blood cancer screening.",
    icon: "droplets",
    color: "#dc2626",
    href: "/services/hematology-services",
  },
  {
    id: 4,
    title: "Hormone & Immunology Tests",
    description: "Precise measurement of hormones and immune markers for endocrine and autoimmune condition management.",
    icon: "shield",
    color: "#8b5cf6",
    href: "/services/hormone-immunology-tests",
  },
  {
    id: 5,
    title: "Urine & Stool Analysis",
    description: "Non-invasive diagnostic testing to detect infections, kidney issues, and digestive health concerns.",
    icon: "flask-conical",
    color: "#06b6d4",
    href: "/services/urine-stool-analysis",
  },
  {
    id: 6,
    title: "Digital X-Ray",
    description: "High-resolution imaging for bones, chest, and internal organs with minimal radiation exposure.",
    icon: "scan",
    color: "#6366f1",
    href: "/services/digital-x-ray",
  },
  {
    id: 7,
    title: "Ultrasonography (USG)",
    description: "Safe, real-time imaging for abdominal, pelvic, vascular, and prenatal examinations.",
    icon: "waves",
    color: "#14b8a6",
    href: "/services/ultrasonography-usg",
  },
  {
    id: 8,
    title: "Color Doppler Imaging",
    description: "Advanced ultrasound technology to visualize blood flow and detect vascular abnormalities.",
    icon: "activity",
    color: "#0ea5e9",
    href: "/services/color-doppler-imaging",
  },
  {
    id: 9,
    title: "ECG (Electrocardiogram)",
    description: "Quick, painless heart rhythm monitoring to detect arrhythmias, heart attacks, and cardiac conditions.",
    icon: "heart-pulse",
    color: "#ef4444",
    href: "/services/ecg-electrocardiogram",
  },
  {
    id: 10,
    title: "Echocardiography (ECHO)",
    description: "Detailed ultrasound imaging of heart structure and function for comprehensive cardiac assessment.",
    icon: "heart",
    color: "#f43f5e",
    href: "/services/echocardiography-echo",
  },
  {
    id: 11,
    title: "CT Scan Services",
    description: "Cross-sectional imaging for detailed views of bones, blood vessels, and soft tissues.",
    icon: "scan",
    color: "#8b5cf6",
    href: "/services/ct-scan-services",
  },
  {
    id: 12,
    title: "MRI Scan Services",
    description: "High-definition magnetic resonance imaging for brain, spine, joints, and soft tissue evaluation.",
    icon: "scan-line",
    color: "#7c3aed",
    href: "/services/mri-scan-services",
  },
  {
    id: 13,
    title: "Mammography",
    description: "Specialized low-dose X-ray imaging for early detection and screening of breast cancer.",
    icon: "heart",
    color: "#ec4899",
    href: "/services/mammography",
  },
  {
    id: 14,
    title: "Endoscopy & Colonoscopy",
    description: "Minimally invasive procedures to examine and treat conditions of the digestive tract.",
    icon: "scan-search",
    color: "#059669",
    href: "/services/endoscopy-colonoscopy",
  },
  {
    id: 15,
    title: "Pulmonary Function Test (PFT)",
    description: "Comprehensive lung function assessment for asthma, COPD, and respiratory disorder diagnosis.",
    icon: "wind",
    color: "#0ea5e9",
    href: "/services/pulmonary-function-test-pft",
  },
  {
    id: 16,
    title: "EEG & EMG Testing",
    description: "Neurological diagnostics to evaluate brain activity and nerve-muscle function for seizure and neuropathy assessment.",
    icon: "brain",
    color: "#6366f1",
    href: "/services/eeg-emg-testing",
  },
  {
    id: 17,
    title: "Cardiology Diagnostic Services",
    description: "Complete heart health evaluation including stress tests, Holter monitoring, and advanced cardiac imaging.",
    icon: "heart-pulse",
    color: "#e53e3e",
    href: "/services/cardiology-diagnostic-services",
  },
  {
    id: 18,
    title: "Diabetes Screening & Management",
    description: "Comprehensive glucose testing, HbA1c monitoring, and personalized diabetes care planning.",
    icon: "droplet",
    color: "#f59e0b",
    href: "/services/diabetes-screening-management",
  },
  {
    id: 19,
    title: "Kidney Function Tests",
    description: "Essential blood and urine tests to evaluate kidney health and detect renal disorders early.",
    icon: "droplets",
    color: "#06b6d4",
    href: "/services/kidney-function-tests",
  },
  {
    id: 20,
    title: "Liver Function Tests",
    description: "Critical blood panels to assess liver health, detect hepatitis, and monitor treatment effectiveness.",
    icon: "flask-conical",
    color: "#84cc16",
    href: "/services/liver-function-tests",
  },
  {
    id: 21,
    title: "Thyroid Profile Tests",
    description: "Accurate thyroid hormone testing for diagnosing hypothyroidism, hyperthyroidism, and metabolic disorders.",
    icon: "activity",
    color: "#22c55e",
    href: "/services/thyroid-profile-tests"
  },
  {
    id: 22,
    title: "Cancer Screening",
    description: "Early detection programs using advanced markers and imaging for various cancer types.",
    icon: "ribbon",
    color: "#ec4899",
    href: "/services/cancer-screening",
  },
  {
    id: 23,
    title: "Preventive Health Checkup Packages",
    description: "Customized wellness packages designed to identify health risks before symptoms appear.",
    icon: "shield-check",
    color: "#10b981",
    href: "/services/preventive-health-checkup-packages",
  },
  {
    id: 24,
    title: "Full Body Health Checkup",
    description: "Comprehensive head-to-toe evaluation covering all major organ systems for complete health assessment.",
    icon: "user-check",
    color: "#3b82f6",
    href: "/services/full-body-health-checkup",
  },
  {
    id: 25,
    title: "Covid-19 & Viral Screening",
    description: "Rapid and PCR testing for coronavirus and other viral infections with quick, reliable results.",
    icon: "virus",
    color: "#ef4444",
    href: "/services/covid-19-viral-screening",
  },
  {
    id: 26,
    title: "Home Sample Collection",
    description: "Convenient at-home blood and specimen collection by trained phlebotomists for your comfort.",
    icon: "home",
    color: "#f97316",
    href: "/services/home-sample-collection",
  },
  {
    id: 27,
    title: "Doctor Consultation Services",
    description: "Easy access to experienced physicians for diagnosis, treatment planning, and health guidance.",
    icon: "stethoscope",
    color: "#6366f1",
    href: "/services/doctor-consultation-services",
  },
  {
    id: 28,
    title: "Specialist Chamber Services",
    description: "Dedicated consultation rooms with expert specialists across multiple medical disciplines.",
    icon: "building",
    color: "#05417d",
    href: "/services/specialist-chamber-services",
  },
  {
    id: 29,
    title: "Women's Health Diagnostics",
    description: "Specialized screening and testing for reproductive health, hormonal balance, and women-specific conditions.",
    icon: "heart",
    color: "#ec4899",
    href: "/services/womens-health-diagnostics",
  },
  {
    id: 30,
    title: "Child Health Diagnostics",
    description: "Gentle, age-appropriate diagnostic services tailored for infants, children, and adolescents.",
    icon: "baby",
    color: "#f59e0b",
    href: "/services/child-health-diagnostics",
  },
  {
    id: 31,
    title: "Prenatal & Pregnancy Checkups",
    description: "Comprehensive maternal care including ultrasounds, genetic screening, and pregnancy monitoring.",
    icon: "baby",
    color: "#8b5cf6",
    href: "/services/prenatal-pregnancy-checkups",
  },
  {
    id: 32,
    title: "Health Screening for Corporate Clients",
    description: "Customized employee wellness programs with on-site or clinic-based health assessments.",
    icon: "users",
    color: "#14b8a6",
    href: "/services/health-screening-corporate-clients",
  },
  {
    id: 33,
    title: "Emergency Diagnostic Support",
    description: "Rapid testing and imaging services available 24/7 for urgent and critical care situations.",
    icon: "alarm",
    color: "#dc2626",
    href: "/services/emergency-diagnostic-support",
  },
  {
    id: 34,
    title: "Digital Reporting & Online Reports",
    description: "Secure, instant access to your test results via our patient portal with expert interpretation.",
    icon: "file-check",
    color: "#22c55e",
    href: "/services/digital-reporting-online-reports",
  },
];

export const doctors = [
  {
    id: 1,
    name: "Fariha Rahman",
    specialty: "Cardiologist",
    qualification: "MBBS, MD (Cardiology), FCPS",
    experience: "18 Years",
    image: "/images/doctors/doctor-1.jpg",
    available: "Mon, Wed, Thu",
    rating: 4.9,
    patients: "3,200+",
    gender: "Female",
    branch: "Gulshan Branch",
    branchId: "dhaka-main",
    consultationType: "Video / Audio Call",

    // ✅ CORRECTED FIELDS FOR DOCTOR #1
    title: "Senior Cardiologist",
    department: "Cardiology",
    reviewCount: 128,
    languages: ["Bengali", "English"],
    bio: "Dr. Fariha Rahman is a board-certified cardiologist with over 18 years of experience in diagnosing and treating complex heart conditions. She completed her MD at Bangabandhu Sheikh Mujib Medical University and received advanced training in interventional cardiology at Apollo Hospitals, India.",
    specialties: ["Heart Failure", "Interventional Cardiology", "Preventive Cardiology"],
    availableDays: ["Mon", "Wed", "Thu"],
    availableTimes: ["9:00 AM - 1:00 PM", "5:00 PM - 8:00 PM"],
    consultationFee: 1500,
    education: [
      { year: "2005", degree: "MBBS", institution: "Dhaka Medical College" },
      { year: "2010", degree: "MD (Cardiology)", institution: "BSMMU, Dhaka" },
      { year: "2015", degree: "FCPS", institution: "College of Physicians & Surgeons, Bangladesh" },
    ],
    certifications: [
      "BMDC Registered (A-12345)",
      "Fellow of the American College of Cardiology (FACC)",
      "Certified in Advanced Cardiac Life Support (ACLS)",
    ],
    reviews: [
      {
        id: 1,
        patient: "Rina Begum",
        date: "2025-04-10",
        rating: 5,
        comment: "Dr. Fariha explained my condition very clearly. The treatment plan worked perfectly. Highly recommended!",
      },
      {
        id: 2,
        patient: "Kamal Hossain",
        date: "2025-03-28",
        rating: 5,
        comment: "Very professional and caring. Took time to answer all my questions. Excellent service.",
      },
    ],
    location: "House #12, Gulshan 2, Dhaka-1212, Bangladesh",
    phone: "+880 1700-000000",
    email: "dr.fariha@renovalifecare.com",
  },

  {
    id: 2,
    name: "Tasnim Farin",
    specialty: "Neurologist",
    qualification: "MBBS, MD (Neurology), PhD",
    experience: "22 Years",
    image: "/images/doctors/doctor-2.jpg",
    available: "Sun, Mon, Sat",
    rating: 4.8,
    patients: "2,800+",
    gender: "Female",
    branch: "Gulshan Branch",
    branchId: "dhaka-main",
    consultationType: "Video / Audio Call",

    // ✅ UNIQUE DATA FOR DOCTOR #2 - NEUROLOGIST
    title: "Senior Neurologist",
    department: "Neurology",
    reviewCount: 96,
    languages: ["Bengali", "English", "Hindi"],
    bio: "Dr. Tasnim Farin is a distinguished neurologist specializing in epilepsy, stroke, and movement disorders. She completed her PhD in Neuroscience at University of Tokyo and has published over 40 research papers.",
    specialties: ["Epilepsy Management", "Stroke Care", "Parkinson's Disease", "Neuropathy"],
    availableDays: ["Sun", "Mon", "Sat"],
    availableTimes: ["10:00 AM - 2:00 PM", "6:00 PM - 9:00 PM"],
    consultationFee: 1800,
    education: [
      { year: "2003", degree: "MBBS", institution: "Dhaka Medical College" },
      { year: "2008", degree: "MD (Neurology)", institution: "BSMMU, Dhaka" },
      { year: "2012", degree: "PhD (Neuroscience)", institution: "University of Tokyo, Japan" },
    ],
    certifications: [
      "BMDC Registered (A-23456)",
      "Member of Bangladesh Neurological Society",
      "Certified in Stroke Management (AHA)",
    ],
    reviews: [
      {
        id: 1,
        patient: "Abdullah Al-Mamun",
        date: "2025-04-05",
        rating: 5,
        comment: "Dr. Tasnim is incredibly knowledgeable. She diagnosed my father's condition quickly and the treatment is working well.",
      },
      {
        id: 2,
        patient: "Nasrin Akter",
        date: "2025-03-20",
        rating: 4,
        comment: "Very thorough examination. Explained everything in simple terms. Highly recommend for neurological issues.",
      },
    ],
    location: "House #12, Gulshan 2, Dhaka-1212, Bangladesh",
    phone: "+880 1700-000001",
    email: "dr.tasnim@renovalifecare.com",
  },

  {
    id: 3,
    name: "Aysha Aktar Tripti",
    specialty: "Pediatrician",
    qualification: "MBBS, DCH, FCPS (Pediatrics)",
    experience: "15 Years",
    image: "/images/doctors/doctor-3.jpg",
    available: "Tue, Wed, Sat",
    rating: 4.9,
    patients: "4,100+",
    gender: "Female",
    branch: "Mirpur Branch",
    branchId: "mirpur",
    consultationType: "Video / Audio Call",

    // ✅ UNIQUE DATA FOR DOCTOR #3 - PEDIATRICIAN
    title: "Senior Pediatrician",
    department: "Pediatrics",
    reviewCount: 215,
    languages: ["Bengali", "English"],
    bio: "Dr. Aysha Aktar Tripti is a compassionate pediatrician dedicated to children's health from newborn to adolescence. She specializes in vaccination, nutrition, and developmental care.",
    specialties: ["Newborn Care", "Child Vaccination", "Growth & Development", "Pediatric Nutrition"],
    availableDays: ["Tue", "Wed", "Sat"],
    availableTimes: ["8:00 AM - 12:00 PM", "4:00 PM - 7:00 PM"],
    consultationFee: 1200,
    education: [
      { year: "2009", degree: "MBBS", institution: "Sir Salimullah Medical College" },
      { year: "2012", degree: "DCH", institution: "Bangladesh College of Physicians & Surgeons" },
      { year: "2015", degree: "FCPS (Pediatrics)", institution: "BCPS, Dhaka" },
    ],
    certifications: [
      "BMDC Registered (A-34567)",
      "Certified in Pediatric Advanced Life Support (PALS)",
      "Member of Bangladesh Pediatric Association",
    ],
    reviews: [
      {
        id: 1,
        patient: "Rafiqul Karim",
        date: "2025-04-12",
        rating: 5,
        comment: "Dr. Aysha is amazing with kids! My son was scared of doctors but she made him feel comfortable. Great care!",
      },
      {
        id: 2,
        patient: "Sadia Islam",
        date: "2025-04-01",
        rating: 5,
        comment: "Very patient and knowledgeable. She answered all my questions about my baby's development. Highly recommended!",
      },
    ],
    location: "House #45, Mirpur-10, Dhaka-1216, Bangladesh",
    phone: "+880 1700-000002",
    email: "dr.aysha@renovalifecare.com",
  },

  {
    id: 4,
    name: "Humayon Kabir",
    specialty: "Orthopedic Surgeon",
    qualification: "MBBS, MS (Orthopedics), FRCS",
    experience: "20 Years",
    image: "/images/doctors/doctor-4.jpg",
    available: "Mon, Thu, Sat",
    rating: 4.7,
    patients: "2,500+",
    gender: "Male",
    branch: "Gulshan Branch",
    branchId: "dhaka-main",
    consultationType: "Face to Face",

    // ✅ UNIQUE DATA FOR DOCTOR #4 - ORTHOPEDIC SURGEON
    title: "Senior Orthopedic Surgeon",
    department: "Orthopedics",
    reviewCount: 87,
    languages: ["Bengali", "English"],
    bio: "Dr. Humayon Kabir is an expert orthopedic surgeon specializing in joint replacement, sports injuries, and trauma care. He has performed over 2,000 successful surgeries.",
    specialties: ["Joint Replacement", "Sports Injury", "Spine Surgery", "Fracture Care"],
    availableDays: ["Mon", "Thu", "Sat"],
    availableTimes: ["9:00 AM - 1:00 PM", "4:00 PM - 7:00 PM"],
    consultationFee: 2000,
    education: [
      { year: "2004", degree: "MBBS", institution: "Rajshahi Medical College" },
      { year: "2009", degree: "MS (Orthopedics)", institution: "BSMMU, Dhaka" },
      { year: "2014", degree: "FRCS", institution: "Royal College of Surgeons, UK" },
    ],
    certifications: [
      "BMDC Registered (A-45678)",
      "Fellow of the Royal College of Surgeons (FRCS)",
      "Certified in Arthroscopic Surgery",
    ],
    reviews: [
      {
        id: 1,
        patient: "Sumaiya Jahan",
        date: "2025-04-08",
        rating: 5,
        comment: "After years of knee pain, Dr. Humayon's surgery gave me my life back. Professional and caring. Thank you!",
      },
      {
        id: 2,
        patient: "Mahmud Hasan",
        date: "2025-03-25",
        rating: 4,
        comment: "Very skilled surgeon. Explained the procedure clearly. Recovery was smooth. Recommended!",
      },
    ],
    location: "House #12, Gulshan 2, Dhaka-1212, Bangladesh",
    phone: "+880 1700-000003",
    email: "dr.humayon@renovalifecare.com",
  },

  {
    id: 5,
    name: "Nasreen Akter",
    specialty: "Cardiologist",
    qualification: "MBBS, MD (Cardiology), FCPS",
    experience: "18 Years",
    image: "/images/doctors/doctor-5.jpg",
    available: "Mon, Wed, Thu",
    rating: 4.9,
    patients: "3,200+",
    gender: "Female",
    branch: "Gulshan Branch",
    branchId: "dhaka-main",
    consultationType: "Video / Audio Call",

    // ✅ UNIQUE DATA FOR DOCTOR #5 - CARDIOLOGIST
    title: "Senior Cardiologist",
    department: "Cardiology",
    reviewCount: 142,
    languages: ["Bengali", "English"],
    bio: "Dr. Nasreen Akter specializes in preventive cardiology and women's heart health. She focuses on early detection and personalized treatment plans for cardiovascular diseases.",
    specialties: ["Preventive Cardiology", "Women's Heart Health", "Hypertension Management", "Lipid Disorders"],
    availableDays: ["Mon", "Wed", "Thu"],
    availableTimes: ["10:00 AM - 2:00 PM", "5:00 PM - 8:00 PM"],
    consultationFee: 1500,
    education: [
      { year: "2006", degree: "MBBS", institution: "Dhaka Medical College" },
      { year: "2011", degree: "MD (Cardiology)", institution: "BSMMU, Dhaka" },
      { year: "2016", degree: "FCPS", institution: "College of Physicians & Surgeons, Bangladesh" },
    ],
    certifications: [
      "BMDC Registered (A-56789)",
      "Certified in Echocardiography",
      "Member of Bangladesh Cardiac Society",
    ],
    reviews: [
      {
        id: 1,
        patient: "Rina Begum",
        date: "2025-04-10",
        rating: 5,
        comment: "Dr. Nasreen is wonderful! She took time to explain my heart condition and the treatment options. Very caring!",
      },
      {
        id: 2,
        patient: "Kamal Hossain",
        date: "2025-03-30",
        rating: 5,
        comment: "Excellent cardiologist. My blood pressure is now under control thanks to her guidance. Highly recommend!",
      },
    ],
    location: "House #12, Gulshan 2, Dhaka-1212, Bangladesh",
    phone: "+880 1700-000004",
    email: "dr.nasreen@renovalifecare.com",
  },

  {
    id: 6,
    name: "Katrina Kaif",
    specialty: "Neurologist",
    qualification: "MBBS, MD (Neurology), PhD",
    experience: "22 Years",
    image: "/images/doctors/doctor-6.jpg",
    available: "Sun, Mon, Sat",
    rating: 4.8,
    patients: "2,800+",
    gender: "Female",
    branch: "Gulshan Branch",
    branchId: "dhaka-main",
    consultationType: "Video / Audio Call",

    // ✅ UNIQUE DATA FOR DOCTOR #6 - NEUROLOGIST
    title: "Consultant Neurologist",
    department: "Neurology",
    reviewCount: 103,
    languages: ["Bengali", "English", "Urdu"],
    bio: "Dr. Katrina Kaif is a renowned neurologist with expertise in headache disorders, multiple sclerosis, and neuro-rehabilitation. She advocates for holistic patient care.",
    specialties: ["Headache & Migraine", "Multiple Sclerosis", "Neuro-Rehabilitation", "Sleep Disorders"],
    availableDays: ["Sun", "Mon", "Sat"],
    availableTimes: ["11:00 AM - 3:00 PM", "6:00 PM - 9:00 PM"],
    consultationFee: 1700,
    education: [
      { year: "2002", degree: "MBBS", institution: "Chittagong Medical College" },
      { year: "2007", degree: "MD (Neurology)", institution: "BSMMU, Dhaka" },
      { year: "2013", degree: "PhD (Neurology)", institution: "King's College London, UK" },
    ],
    certifications: [
      "BMDC Registered (A-67890)",
      "Certified in Neuro-Rehabilitation",
      "Member of World Federation of Neurology",
    ],
    reviews: [
      {
        id: 1,
        patient: "Tahmina Akter",
        date: "2025-04-07",
        rating: 5,
        comment: "Dr. Katrina helped me manage my migraines effectively. Very empathetic and knowledgeable. Thank you!",
      },
      {
        id: 2,
        patient: "Rahim Uddin",
        date: "2025-03-22",
        rating: 4,
        comment: "Good consultation. She explained my condition clearly and the treatment is helping. Recommended!",
      },
    ],
    location: "House #12, Gulshan 2, Dhaka-1212, Bangladesh",
    phone: "+880 1700-000005",
    email: "dr.katrina@renovalifecare.com",
  },

  {
    id: 7,
    name: "Alifa Aktar",
    specialty: "Pediatrician",
    qualification: "MBBS, DCH, FCPS (Pediatrics)",
    experience: "15 Years",
    image: "/images/doctors/doctor-7.jpg",
    available: "Tue, Wed, Sat",
    rating: 4.9,
    patients: "4,100+",
    gender: "Female",
    branch: "Mirpur Branch",
    branchId: "mirpur",
    consultationType: "Video / Audio Call",

    // ✅ UNIQUE DATA FOR DOCTOR #7 - PEDIATRICIAN
    title: "Pediatric Consultant",
    department: "Pediatrics",
    reviewCount: 189,
    languages: ["Bengali", "English"],
    bio: "Dr. Alifa Aktar is a gentle and experienced pediatrician focusing on infant care, childhood illnesses, and adolescent health. She believes in family-centered care.",
    specialties: ["Infant Care", "Childhood Asthma", "Adolescent Health", "Developmental Screening"],
    availableDays: ["Tue", "Wed", "Sat"],
    availableTimes: ["9:00 AM - 1:00 PM", "5:00 PM - 8:00 PM"],
    consultationFee: 1200,
    education: [
      { year: "2010", degree: "MBBS", institution: "Sylhet MAG Osmani Medical College" },
      { year: "2013", degree: "DCH", institution: "Bangladesh College of Physicians & Surgeons" },
      { year: "2016", degree: "FCPS (Pediatrics)", institution: "BCPS, Dhaka" },
    ],
    certifications: [
      "BMDC Registered (A-78901)",
      "Certified in Pediatric Asthma Management",
      "Member of Bangladesh Pediatric Association",
    ],
    reviews: [
      {
        id: 1,
        patient: "Fatema Khatun",
        date: "2025-04-11",
        rating: 5,
        comment: "Dr. Alifa is so kind with children! My daughter loves visiting her. Very thorough and caring doctor.",
      },
      {
        id: 2,
        patient: "Mohammad Ali",
        date: "2025-04-02",
        rating: 5,
        comment: "Excellent pediatrician. She diagnosed my son's allergy quickly and the treatment worked perfectly!",
      },
    ],
    location: "House #45, Mirpur-10, Dhaka-1216, Bangladesh",
    phone: "+880 1700-000006",
    email: "dr.alifa@renovalifecare.com",
  },

  {
    id: 8,
    name: "Maria Hoque",
    specialty: "Orthopedic Surgeon",
    qualification: "MBBS, MS (Orthopedics), FRCS",
    experience: "20 Years",
    image: "/images/doctors/doctor-8.jpg",
    available: "Mon, Thu, Sat",
    rating: 4.7,
    patients: "2,500+",
    gender: "Female",
    branch: "Dhanmondi Branch",
    branchId: "dhanmondi",
    consultationType: "Video / Audio Call",

    // ✅ UNIQUE DATA FOR DOCTOR #8 - ORTHOPEDIC SURGEON
    title: "Orthopedic Consultant",
    department: "Orthopedics",
    reviewCount: 76,
    languages: ["Bengali", "English"],
    bio: "Dr. Maria Hoque is a skilled orthopedic surgeon specializing in minimally invasive procedures, pediatric orthopedics, and sports medicine. She prioritizes patient recovery and mobility.",
    specialties: ["Minimally Invasive Surgery", "Pediatric Orthopedics", "Sports Medicine", "Hand Surgery"],
    availableDays: ["Mon", "Thu", "Sat"],
    availableTimes: ["10:00 AM - 2:00 PM", "5:00 PM - 8:00 PM"],
    consultationFee: 1900,
    education: [
      { year: "2005", degree: "MBBS", institution: "Dhaka Medical College" },
      { year: "2010", degree: "MS (Orthopedics)", institution: "BSMMU, Dhaka" },
      { year: "2015", degree: "FRCS", institution: "Royal College of Surgeons, Edinburgh" },
    ],
    certifications: [
      "BMDC Registered (A-89012)",
      "Certified in Arthroscopic & Minimally Invasive Surgery",
      "Member of Bangladesh Orthopaedic Association",
    ],
    reviews: [
      {
        id: 1,
        patient: "Karim Ahmed",
        date: "2025-04-09",
        rating: 5,
        comment: "Dr. Maria performed my wrist surgery with great skill. Recovery was faster than expected. Very professional!",
      },
      {
        id: 2,
        patient: "Nusrat Jahan",
        date: "2025-03-27",
        rating: 4,
        comment: "Good experience. She explained the treatment options clearly. My shoulder pain has improved significantly.",
      },
    ],
    location: "House #78, Dhanmondi-32, Dhaka-1209, Bangladesh",
    phone: "+880 1700-000007",
    email: "dr.maria@renovalifecare.com",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Rina Begum",
    location: "Mirpur, Dhaka",
    rating: 5,
    review:
      "Renova Life Care has completely changed my view of healthcare in Bangladesh. The doctors are incredibly knowledgeable, the staff is warm, and the facilities are spotless. My mother received excellent cardiac care here.",
    service: "Cardiology",
    avatar: "/images/testimonials/patient-1.jpg",
  },
  {
    id: 2,
    name: "Rafiqul Karim",
    location: "Chittagong",
    rating: 5,
    review:
      "I traveled from Chittagong specifically for my son's treatment at Renova. Dr. Nasreen is phenomenal with children. The online appointment system is very convenient. Highly recommended!",
    service: "Pediatrics",
    avatar: "/images/testimonials/patient-2.jpg",
  },
  {
    id: 3,
    name: "Sumaiya Jahan",
    location: "Uttara, Dhaka",
    rating: 5,
    review:
      "The orthopedic department is world-class. After years of knee pain, Dr. Mahmudul's surgery has given me my life back. Professional, caring, and truly life-changing.",
    service: "Orthopedics",
    avatar: "/images/testimonials/patient-3.jpg",
  },
  {
    id: 4,
    name: "Abdullah Al-Mamun",
    location: "Sylhet",
    rating: 4,
    review:
      "Excellent neurological care from Dr. Tariq. He explained everything clearly, listened patiently, and the treatment plan has been very effective. Clean environment and punctual appointments.",
    service: "Neurology",
    avatar: "/images/testimonials/patient-4.jpg",
  },
];

export const shopProducts = [
  {
    id: 1,
    name: "Digital Blood Pressure Monitor",
    price: 2800,
    oldPrice: 3500,
    rating: 4.8,
    reviews: 142,
    image: "/images/shop/image1.jpg",
    badge: "Best Seller",
    category: "Devices",
  },
  {
    id: 2,
    name: "Diabetic Care Kit",
    price: 1200,
    oldPrice: null,
    rating: 4.7,
    reviews: 89,
    image: "/images/shop/image2.jpg",
    badge: "New",
    category: "Health Kits",
  },
  {
    id: 3,
    name: "Omega-3 Fish Oil (90 Capsules)",
    price: 850,
    oldPrice: 1100,
    rating: 4.9,
    reviews: 234,
    image: "/images/shop/image3.jpg",
    badge: "20% Off",
    category: "Supplements",
  },
  {
    id: 4,
    name: "Pulse Oximeter",
    price: 1500,
    oldPrice: null,
    rating: 4.6,
    reviews: 67,
    image: "/images/shop/image4.jpg",
    badge: null,
    category: "Devices",
  },
];

export const portfolioItems = [
  {
    id: 1,
    title: "State-of-the-Art ICU",
    category: "Facilities",
    image: "/images/portfolio/image1.jpg",
  },
  {
    id: 2,
    title: "Modern Operating Theater",
    category: "Surgery",
    image: "/images/portfolio/image2.jpg",
  },
  {
    id: 3,
    title: "Advanced Diagnostic Lab",
    category: "Diagnostics",
    image: "/images/portfolio/image3.jpg",
  },
  {
    id: 4,
    title: "Pediatric Care Ward",
    category: "Pediatrics",
    image: "/images/portfolio/image4.jpg",
  },
  {
    id: 5,
    title: "Rehabilitation Center",
    category: "Rehabilitation",
    image: "/images/portfolio/image5.jpg",
  },
  {
    id: 6,
    title: "Digital Pharmacy",
    category: "Pharmacy",
    image: "/images/portfolio/image6.jpg",
  },
];

export const blogs = [
  {
    id: 1,
    title: "10 Early Warning Signs of Heart Disease You Shouldn't Ignore",
    excerpt:
      "Cardiovascular disease remains the leading cause of death worldwide. Learn the warning signs that require immediate medical attention.",
    category: "Cardiology",
    date: "April 15, 2025",
    readTime: "5 min read",
    author: "Dr. Fariha Rahman",
    image: "/images/blog/heart-disease.jpg",
    href: "/blog/heart-disease-warning-signs",
  },
  {
    id: 2,
    title: "Managing Diabetes in Bangladesh: A Practical Guide",
    excerpt:
      "With rising diabetes rates in Bangladesh, here's how to manage your blood sugar through diet, exercise, and medication.",
    category: "Diabetes",
    date: "April 8, 2025",
    readTime: "7 min read",
    author: "Dr. Tariq Hossain",
    image: "/images/blog/diabetes.jpg",
    href: "/blog/managing-diabetes-bangladesh",
  },
  {
    id: 3,
    title: "Your Child's Vaccination Schedule: A Complete Guide",
    excerpt:
      "Keeping up with childhood vaccinations is crucial. Here's everything Bangladeshi parents need to know about the EPI schedule.",
    category: "Pediatrics",
    date: "March 30, 2025",
    readTime: "6 min read",
    author: "Dr. Nasreen Akter",
    image: "/images/blog/vaccination.jpg",
    href: "/blog/vaccination-schedule-guide",
  },
];

export const partners = [
  { id: 1, name: "Square Hospitals", logo: "/images/partners/01.png" },
  { id: 2, name: "Beximco Pharma", logo: "/images/partners/02.png" },
  { id: 3, name: "DGDA Bangladesh", logo: "/images/partners/03.png" },
  { id: 4, name: "WHO Bangladesh", logo: "/images/partners/03.png" },
  { id: 5, name: "BSMMU", logo: "/images/partners/05.png" },
  { id: 6, name: "Bangladesh Medical Association", logo: "/images/partners/06.png" },
];

export const whyChooseUs = [
  {
    id: 1,
    title: "Certified Expert Doctors",
    description: "All our physicians are BMDC-registered with international training and decades of experience.",
    icon: "shield-check",
  },
  {
    id: 2,
    title: "Modern Technology",
    description: "Latest diagnostic equipment including MRI, CT Scan, and digital pathology for accurate results.",
    icon: "cpu",
  },
  {
    id: 3,
    title: "Patient-First Care",
    description: "Every treatment plan is personalized. We listen, understand, and treat the whole person.",
    icon: "heart-handshake",
  },
  {
    id: 4,
    title: "24/7 Emergency",
    description: "Round-the-clock emergency services with dedicated critical care units ready at all times.",
    icon: "alarm",
  },
];